/**
 * City population lookup.
 *
 * Data is bundled (src/lib/geo/city-populations.json, generated by
 * scripts/build-city-populations.mjs from a GeoNames dump) — no runtime API
 * calls, no key. Server-side only: the JSON is a few MB and must never end up
 * in the client bundle. The browser gets it a state at a time through
 * /api/geo/city-populations.
 *
 * Joining to `country-state-city` is by normalized name first, then by lat/lng
 * proximity. Both datasets descend from GeoNames, so coordinates usually match
 * to several decimals and the fallback catches the name spelling differences.
 */

import { City } from "country-state-city";
import type { ICity } from "country-state-city";
import raw from "./city-populations.json";

/** [normalizedName, population, lat, lng] */
type PopRow = [string, number, number, number];
type PopData = Record<string, Record<string, PopRow[]>>;

const DATA = raw as unknown as PopData;

/** True once the dataset has actually been generated (placeholder is `{}`). */
export const hasPopulationData = Object.keys(DATA).length > 0;

// Keep in sync with normalizeCityName() in scripts/build-city-populations.mjs
export function normalizeCityName(name: string): string {
  return name
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/\bsaint\b/g, "st")
    .replace(/\bsainte\b/g, "st")
    .replace(/\bmount\b/g, "mt")
    .replace(/\bfort\b/g, "ft")
    .replace(/[^a-z0-9]/g, "");
}

/** ~0.15° ≈ 16 km. Loose enough for centroid drift, tight enough to not grab a neighbour. */
const MAX_COORD_DELTA = 0.15;

const stateCache = new Map<string, Record<string, number>>();

/**
 * Population for every city `country-state-city` knows about in this state,
 * keyed by that package's exact city name so callers can look up directly.
 * Cities with no match are simply absent.
 */
export function getStateCityPopulations(
  countryCode: string,
  stateCode: string
): Record<string, number> {
  const cacheKey = `${countryCode}:${stateCode}`;
  const cached = stateCache.get(cacheKey);
  if (cached) return cached;

  const rows = DATA[countryCode]?.[stateCode] ?? [];
  const result: Record<string, number> = {};
  if (rows.length === 0) {
    stateCache.set(cacheKey, result);
    return result;
  }

  // Rows are sorted population-desc by the build script, so the first write for
  // a normalized name is the largest place — don't let a smaller one clobber it.
  const byName = new Map<string, PopRow>();
  for (const row of rows) {
    if (!byName.has(row[0])) byName.set(row[0], row);
  }

  for (const city of City.getCitiesOfState(countryCode, stateCode)) {
    if (!city?.name) continue;

    const hit = byName.get(normalizeCityName(city.name));
    if (hit) {
      result[city.name] = hit[1];
      continue;
    }

    // Name miss → nearest place within the radius wins.
    const lat = city.latitude ? parseFloat(city.latitude) : NaN;
    const lng = city.longitude ? parseFloat(city.longitude) : NaN;
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;

    let best: PopRow | null = null;
    let bestDist = Infinity;
    for (const row of rows) {
      const dLat = Math.abs(row[2] - lat);
      if (dLat > MAX_COORD_DELTA) continue;
      const dLng = Math.abs(row[3] - lng);
      if (dLng > MAX_COORD_DELTA) continue;
      const dist = dLat * dLat + dLng * dLng;
      if (dist < bestDist) {
        bestDist = dist;
        best = row;
      }
    }
    if (best) result[city.name] = best[1];
  }

  stateCache.set(cacheKey, result);
  return result;
}

export type CityWithPopulation = ICity & { population: number | null };

/**
 * Cities of a state, largest population first. Cities with no population data
 * sort last, alphabetically among themselves. Falls back to plain alphabetical
 * order when the dataset hasn't been generated yet.
 */
export function getCitiesOfStateByPopulation(
  countryCode: string,
  stateCode: string
): CityWithPopulation[] {
  const cities = City.getCitiesOfState(countryCode, stateCode).filter((c) => c?.name);
  const pops = getStateCityPopulations(countryCode, stateCode);

  return cities
    .map((c) => ({ ...c, population: pops[c.name] ?? null }))
    .sort((a, b) => {
      if (a.population !== null && b.population !== null) return b.population - a.population;
      if (a.population !== null) return -1;
      if (b.population !== null) return 1;
      return a.name.localeCompare(b.name);
    });
}
