// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Match Next.js env precedence so the Prisma CLI (migrate / db push / generate)
// targets the SAME database the app uses: .env.local overrides .env.
// dotenv does not override already-set vars, so the first-loaded file wins and
// the second only fills gaps. On Vercel both files are absent and the
// dashboard-injected process.env vars are used as-is.
config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // POSTGRES_PRISMA_URL      → pooled, injected by Vercel Postgres
    // POSTGRES_URL_NON_POOLING → direct connection, used for migrations
    // DATABASE_URL             → fallback for local development
    url: process.env["POSTGRES_URL_NON_POOLING"] ?? process.env["POSTGRES_PRISMA_URL"] ?? process.env["DATABASE_URL"],
  },
});
