// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // POSTGRES_PRISMA_URL      → pooled, injected by Vercel Postgres
    // POSTGRES_URL_NON_POOLING → direct connection, used for migrations
    // DATABASE_URL             → fallback for local development
    url: process.env["POSTGRES_URL_NON_POOLING"] ?? process.env["POSTGRES_PRISMA_URL"] ?? process.env["DATABASE_URL"],
  },
});
